spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jiangyule?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
logging:
  level:
    com.example.demo: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


minio:
  endpoint: http://192.168.10.101:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: headshot